var myLocalData = [
  {
    title: 'Is That On Purpose?',
    category: 'poetry',
    author: 'Caitlin M Araldi',
    authorUrl: 'https://www.facebook.com/caitlin.araldi',
    publishedOn: '2015-05-11',
    body: '<p>The work truck smelled briefly and overwhelmingly like cotton candy, a surprise only to be absorbed abruptly by the grotesque reality of stale cigarettes and familiar sweat. The gaze was privy to the customary gulping of greed, ready to gobble up an experience for free, without a trace of shame, and with all of the complacency of quotidian vapidness. </p>'
  },
  {
    title: 'PhD Petition',
    category: 'academia',
    author: 'Caitlin M Araldi',
    authorUrl: 'https://www.facebook.com/caitlin.araldi',
    publishedOn: '2015-06-15',
    body: '<p>With great enthusiasm, I submit my petition for direct admission from the M.Ed. program to the Ph.D. program in the Learning Sciences at the University of Washington. My desire to pursue doctoral work resonates with the promise of becoming an active champion for educational change; my belief in the Learning Sciences program to effect this change, and my demonstrated abilities to collaborate and follow through on my commitments to education. I have always been compelled by inquisitiveness about how people learn, and developed a special interest in educational psychology after working as a volunteer teacher of elementary bilingual students  through the Junior Achievement organization. As the student of a second language myself, I uncovered a multi-faceted perspective that motivated me to publish research at the undergraduate level. I dedicated my work to showing the positive results that the many courageous students and teachers under the immense pressure of often conflicting educational directives already demonstrate, without overlooking the call for advancement of their own meaningful goals.</p><p>The process of conducting and recording an investigation without experience within the formal disciplines of psychology or of education was made easier by the gracious involvement of a committee, whose members included Dr. Martha García, Dr. Florin Mihai and Dr. Charles Negy of the University of Central Florida. I was able to not only graduate with a degree in Spanish, but also with published research through the Honors in the Major program. When I submitted my application to the M.Ed. program at the University of Washington in early 2013, I lacked sustained, direct contact with education beyond the context of my degree and volunteer work, but since becoming a student here, have found the opportunity to meaningfully integrate my own passion for socially impactful research with considerable time spent teaching at early learning centers. </p>'
  },
  {
    title: 'The Role of Radicalism',
    category: 'social justice',
    author: 'Caitlin M Araldi',
    authorUrl: 'https://www.facebook.com/caitlin.araldi',
    publishedOn: '2015-09-28',
    body: '<p>The following quote from Perlstein’s article (1990), describing the SNCC’s founding statement of purpose, “‘Non-violence…seeks a social order of justice permeated by love…Justice for all overthrows injustice. The redemptive community supersedes systems of gross social immorality’” (p. 298) especially captured my attention in our readings this week and left me with a few questions (particularly as a secondary source). Does power really lie in knowing, as immense turning points in our history imply? What does “personifying the capacity to overcome racism” (p. 299), or any other grave social threat for that matter, really look like today? It led me to deeply consider the nature of power, and if, as in energy, it can ever truly be created or destroyed. What can collectivity then offer to heal the divides that often result in the operationalization of power as such? The author goes on to elaborate upon the events that I came to see as particularly representative of the power he describes, one in which “truth was not merely studied, but also was lived” (p. 303). The idea of redemption through action continued to jump out at me in various quotes that spoke to the nature of power play in the particular historical context discussed, but also as it applies more broadly. Seeking “truth” in action seems to have a destination by default, but if reflectiveness is the key to meaningful action, it is essential that “removing mental blocks” (p. 299) is perpetual. But how does the nature of those blocks change as evolving socio-historical contexts impact them?</p><p>Certainly with regard to learning in formal environments, the impact of cultural shifts as immense as public schooling can go so far as to shape the very biology of human development and cognition (Culture and Cognitive Development in Phylogenetic, Historical and Ontogenetic Perspective, Michael Cole). The role of “truth” in reality is an incredibly powerful factor—is that synonymous with “knowing”, particularly as achieved through an education? The idea of a “redemptive community” evokes transformation through action in its highest regard, but also implies applicability to “real life”, as opposed to the often de-contextualized implications or promises made by theoretical rhetoric.</p>'
  },
];
